name: todo_firebase_app
description: A simple to-do list app with Firebase

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0

  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  flutter_native_splash: 2.4.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true
assets: block
  - assets/image/


flutter_native_splash:

  color: "#FFFFFF"


  image: assets/image/logo.png

  android_12:
    color: "#FFFFFF"
    image: assets/image/logo.png

